#include "entity/EntitySerialization.hpp"
#include <algorithm>
#include <string>
#include "items/ItemRegistry.hpp"
#include "save/Nbt.hpp"

namespace {
nbt::Tag itemTag(const ItemStack&s,const ItemRegistry* items){nbt::Compound c;if(items){const auto&d=items->get(s.itemId);c["id"]=nbt::Tag(d.name.rfind("minecraft:",0)==0?d.name:"minecraft:"+d.name);}else c["id"]=nbt::Tag(std::to_string(s.itemId));c["BlockcraftItemId"]=nbt::Tag(static_cast<std::int16_t>(s.itemId));c["Count"]=nbt::Tag(static_cast<std::int8_t>(std::clamp(s.count,0,127)));c["Damage"]=nbt::Tag(static_cast<std::int16_t>(s.damage));if(!s.nbt.empty()){try{auto doc=nbt::decode(s.nbt);if(doc.root.type==nbt::Type::Compound)c["tag"]=doc.root;}catch(...){}}return nbt::Tag(std::move(c));}
ItemStack readItem(const nbt::Compound&c,const ItemRegistry* items){ItemStack s;const auto id=nbt::integer(c,"BlockcraftItemId",-1);const ItemDefinition*d=nullptr;if(items&&id>=0&&id<=65535){const auto&x=items->get(static_cast<std::uint16_t>(id));if(x.id==id)d=&x;}if(items&&!d){auto name=nbt::string(c,"id","");d=items->find(name);if(!d&&name.rfind("minecraft:",0)==0)d=items->find(name.substr(10));}if(d)s.itemId=d->id;else if(id>=0&&id<=65535)s.itemId=static_cast<std::uint16_t>(id);else return s;s.count=static_cast<int>(nbt::integer(c,"Count",0));s.damage=static_cast<std::uint16_t>(nbt::integer(c,"Damage",0));if(const auto*t=nbt::find(c,"tag");t&&t->type==nbt::Type::Compound){nbt::Document doc;doc.root=*t;s.nbt=nbt::encode(doc);}return s;}
void common(nbt::Compound&c,const Entity&e){c["id"]=nbt::Tag(e.vanillaId());c["UUIDMost"]=nbt::Tag(static_cast<std::int64_t>(e.uuid.most));c["UUIDLeast"]=nbt::Tag(static_cast<std::int64_t>(e.uuid.least));c["Pos"]=nbt::Tag(nbt::Type::Double,nbt::List{nbt::Tag(e.position.x),nbt::Tag(e.position.y),nbt::Tag(e.position.z)});c["Motion"]=nbt::Tag(nbt::Type::Double,nbt::List{nbt::Tag(e.velocity.x),nbt::Tag(e.velocity.y),nbt::Tag(e.velocity.z)});c["Rotation"]=nbt::Tag(nbt::Type::Float,nbt::List{nbt::Tag(e.yaw),nbt::Tag(e.pitch)});c["Dimension"]=nbt::Tag(static_cast<std::int32_t>(e.dimension));c["TicksExisted"]=nbt::Tag(static_cast<std::int32_t>(e.ticksExisted));}
void readCommon(Entity&e,const nbt::Compound&c){e.uuid.most=static_cast<std::uint64_t>(nbt::integer(c,"UUIDMost",0));e.uuid.least=static_cast<std::uint64_t>(nbt::integer(c,"UUIDLeast",0));if(auto*t=nbt::find(c,"Pos");t&&t->type==nbt::Type::List&&t->list().size()>=3)e.position={std::get<double>(t->list()[0].value),std::get<double>(t->list()[1].value),std::get<double>(t->list()[2].value)};e.previousPosition=e.position;if(auto*t=nbt::find(c,"Motion");t&&t->type==nbt::Type::List&&t->list().size()>=3)e.velocity={std::get<double>(t->list()[0].value),std::get<double>(t->list()[1].value),std::get<double>(t->list()[2].value)};if(auto*t=nbt::find(c,"Rotation");t&&t->type==nbt::Type::List&&t->list().size()>=2){e.yaw=std::get<float>(t->list()[0].value);e.pitch=std::get<float>(t->list()[1].value);e.previousYaw=e.yaw;e.previousPitch=e.pitch;}e.dimension=static_cast<int>(nbt::integer(c,"Dimension",0));e.ticksExisted=static_cast<int>(nbt::integer(c,"TicksExisted",0));}
}
namespace EntitySerialization {
std::vector<std::uint8_t> encode(const Entity&e,const ItemRegistry* items){nbt::Compound c;common(c,e);if(auto*x=dynamic_cast<const EntityItem*>(&e)){c["Health"]=nbt::Tag(static_cast<std::int16_t>(x->health));c["Age"]=nbt::Tag(static_cast<std::int16_t>(x->age));c["PickupDelay"]=nbt::Tag(static_cast<std::int16_t>(x->pickupDelay));c["Item"]=itemTag(x->stack,items);if(!x->owner.empty())c["Owner"]=nbt::Tag(x->owner);if(!x->thrower.empty())c["Thrower"]=nbt::Tag(x->thrower);}else if(auto*x=dynamic_cast<const EntityFallingBlock*>(&e)){c["Block"]=nbt::Tag(static_cast<std::int32_t>(blockId(x->blockState)));c["Data"]=nbt::Tag(static_cast<std::int8_t>(blockMetadata(x->blockState)));c["Time"]=nbt::Tag(static_cast<std::int8_t>(std::clamp(x->fallTime,0,127)));c["DropItem"]=nbt::Tag(static_cast<std::int8_t>(x->dropItem));}else if(auto*x=dynamic_cast<const EntityTNTPrimed*>(&e)){c["Fuse"]=nbt::Tag(static_cast<std::int16_t>(x->fuse));}else if(auto*x=dynamic_cast<const EntityXPOrb*>(&e)){c["Value"]=nbt::Tag(static_cast<std::int16_t>(x->xpValue));c["Age"]=nbt::Tag(static_cast<std::int16_t>(x->age));c["Health"]=nbt::Tag(static_cast<std::int16_t>(x->health));}else if(auto*x=dynamic_cast<const EntityArrow*>(&e)){c["life"]=nbt::Tag(static_cast<std::int16_t>(x->life));c["inGround"]=nbt::Tag(static_cast<std::int8_t>(x->inGround));c["damage"]=nbt::Tag(x->damage);}else if(auto*x=dynamic_cast<const EntityBoat*>(&e)){c["Type"]=nbt::Tag(static_cast<std::int32_t>(x->boatType));}else if(auto*x=dynamic_cast<const EntityMinecart*>(&e)){c["Type"]=nbt::Tag(static_cast<std::int32_t>(x->minecartType));}nbt::Document d;d.root=nbt::Tag(std::move(c));return nbt::encode(d);}
std::unique_ptr<Entity> decode(const std::vector<std::uint8_t>&bytes,const ItemRegistry* items){try{auto d=nbt::decode(bytes);if(d.root.type!=nbt::Type::Compound)return{};const auto&c=d.root.compound();const std::string id=nbt::string(c,"id","");std::unique_ptr<Entity> e;if(id=="minecraft:item"||id=="Item"){auto x=std::make_unique<EntityItem>();x->health=static_cast<int>(nbt::integer(c,"Health",5));x->age=static_cast<int>(nbt::integer(c,"Age",0));x->pickupDelay=static_cast<int>(nbt::integer(c,"PickupDelay",0));if(const auto*t=nbt::find(c,"Item");t&&t->type==nbt::Type::Compound)x->stack=readItem(t->compound(),items);x->owner=nbt::string(c,"Owner","");x->thrower=nbt::string(c,"Thrower","");e=std::move(x);}else if(id=="minecraft:falling_block"||id=="FallingSand"){auto x=std::make_unique<EntityFallingBlock>();x->blockState=makeBlockState(static_cast<std::uint16_t>(nbt::integer(c,"Block",12)),static_cast<std::uint8_t>(nbt::integer(c,"Data",0)));x->fallTime=static_cast<int>(nbt::integer(c,"Time",0));x->dropItem=nbt::boolean(c,"DropItem",true);e=std::move(x);}else if(id=="minecraft:tnt"||id=="PrimedTnt"){auto x=std::make_unique<EntityTNTPrimed>();x->fuse=static_cast<int>(nbt::integer(c,"Fuse",80));e=std::move(x);}else if(id=="minecraft:xp_orb"||id=="XPOrb"){auto x=std::make_unique<EntityXPOrb>();x->xpValue=static_cast<int>(nbt::integer(c,"Value",1));x->age=static_cast<int>(nbt::integer(c,"Age",0));x->health=static_cast<int>(nbt::integer(c,"Health",5));e=std::move(x);}else if(id=="minecraft:arrow"||id=="Arrow"){auto x=std::make_unique<EntityArrow>();x->life=static_cast<int>(nbt::integer(c,"life",0));x->inGround=nbt::boolean(c,"inGround",false);x->damage=nbt::number(c,"damage",2.0);e=std::move(x);}else if(id=="minecraft:boat"||id=="Boat"){auto x=std::make_unique<EntityBoat>();x->boatType=static_cast<int>(nbt::integer(c,"Type",0));e=std::move(x);}else if(id=="minecraft:minecart"||id=="MinecartRideable"){auto x=std::make_unique<EntityMinecart>();x->minecartType=static_cast<int>(nbt::integer(c,"Type",0));e=std::move(x);}if(e)readCommon(*e,c);return e;}catch(...){return{};}}
}
